src/Entity/Member.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\MemberRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Stringable;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: MemberRepository::class)]
class Member implements Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'smallint', options: ['unsigned' => true])]
    private ?int $id = null;

    #[ORM\Column(type: 'uuid', unique: true)]
    private Uuid $uuid;

    #[ORM\Column(type: 'string', length: 100)]
    private string $firstName;

    #[ORM\Column(type: 'string', length: 100)]
    private string $lastName;

    #[ORM\Column(type: 'string', length: 1)]
    private string $gender;

    #[ORM\Column(type: 'date_immutable')]
    private DateTimeImmutable $birthday;

    #[ORM\Column(type: 'string', length: 100)]
    private string $streetAddress;

    #[ORM\Column(type: 'string', length: 10)]
    private string $postCode;

    #[ORM\Column(type: 'string', length: 100)]
    private string $city;

    #[ORM\Column(type: 'string', length: 20, nullable: true)]
    private ?string $phone0 = null;

    #[ORM\Column(type: 'string', length: 20, nullable: true)]
    private ?string $phone1 = null;

    #[ORM\Column(type: 'string', length: 20, nullable: true)]
    private ?string $phone2 = null;

    #[ORM\Column(type: 'string', length: 20, nullable: true)]
    private ?string $phone3 = null;

    #[ORM\OneToMany(mappedBy: 'member', targetEntity: Membership::class)]
    private Collection $memberships;

    #[ORM\OneToMany(mappedBy: 'member', targetEntity: Promotion::class)]
    #[ORM\OrderBy(['nominationDate' => 'ASC'])]
    private Collection $promotions;

    public function __construct()
    {
        $this->memberships = new ArrayCollection();
        $this->promotions = new ArrayCollection();
        $this->uuid = Uuid::v4();
    }

    public function __toString(): string
    {
        return "$this->firstName $this->lastName";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): Uuid
    {
        return $this->uuid;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getBirthday(): DateTimeImmutable
    {
        return $this->birthday;
    }

    public function setBirthday(DateTimeImmutable $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAge(): int
    {
        return (new DateTime())->diff($this->birthday)->y;
    }

    public function getStreetAddress(): string
    {
        return $this->streetAddress;
    }

    public function setStreetAddress(string $streetAddress): self
    {
        $this->streetAddress = $streetAddress;

        return $this;
    }

    public function getPostCode(): string
    {
        return $this->postCode;
    }

    public function setPostCode(string $postCode): self
    {
        $this->postCode = $postCode;

        return $this;
    }

    public function getCity(): string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone0(): ?string
    {
        return $this->phone0;
    }

    public function setPhone0(?string $phone0): self
    {
        $this->phone0 = $phone0;

        return $this;
    }

    public function getPhone1(): ?string
    {
        return $this->phone1;
    }

    public function setPhone1(?string $phone1): self
    {
        $this->phone1 = $phone1;

        return $this;
    }

    public function getPhone2(): ?string
    {
        return $this->phone2;
    }

    public function setPhone2(?string $phone2): self
    {
        $this->phone2 = $phone2;

        return $this;
    }

    public function getPhone3(): ?string
    {
        return $this->phone3;
    }

    public function setPhone3(?string $phone3): self
    {
        $this->phone3 = $phone3;

        return $this;
    }

    /**
     * @return Collection|Membership[]
     */
    public function getMemberships(): ArrayCollection|Collection
    {
        return $this->memberships;
    }

    public function getGender(): string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getLastPromotion(): ?Promotion
    {
        $last = $this->promotions->last();

        return false === $last ? null : $last;
    }
}

src/Form/MemberType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Member;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

final class MemberType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'firstName',
                TextType::class,
                [
                    'attr' => [
                        'autofocus' => true,
                    ],
                    'constraints' => [
                        new Length(min: 1, max: 100),
                    ],
                    'label' => 'field.first_name',
                    'required' => true,
                ]
            )
            ->add(
                'lastName',
                TextType::class,
                [
                    'constraints' => [
                        new Length(min: 1, max: 100),
                    ],
                    'label' => 'field.last_name',
                    'required' => true,
                ]
            )
            ->add(
                'gender',
                ChoiceType::class,
                [
                    'choices' => [
                        'gender.m' => 'm',
                        'gender.f' => 'f',
                    ],
                    'label' => 'field.gender',
                    'required' => true,
                ]
            )
            ->add(
                'birthday',
                BirthdayType::class,
                [
                    'input' => 'datetime_immutable',
                    'label' => 'field.birthday',
                    'required' => true,
                    'widget' => 'single_text',
                ]
            )
            ->add(
                'streetAddress',
                TextType::class,
                [
                    'constraints' => [
                        new Length(min: 1, max: 100),
                    ],
                    'label' => 'field.street_address',
                    'required' => true,
                ]
            )
            ->add(
                'postCode',
                TextType::class,
                [
                    'constraints' => [
                        new Length(min: 1, max: 10),
                    ],
                    'label' => 'field.post_code',
                    'required' => true,
                ]
            )
            ->add(
                'city',
                TextType::class,
                [
                    'constraints' => [
                        new Length(min: 1, max: 100),
                    ],
                    'label' => 'field.city',
                    'required' => true,
                ]
            )
            ->add(
                'phone0',
                TextType::class,
                [
                    'attr' => [
                        'maxlength' => 20,
                    ],
                    'constraints' => [
                        new Length(max: 20),
                    ],
                    'label' => 'field.phone0',
                    'required' => false,
                ]
            )
            ->add(
                'phone1',
                TextType::class,
                [
                    'attr' => [
                        'maxlength' => 20,
                    ],
                    'constraints' => [
                        new Length(max: 20),
                    ],
                    'label' => 'field.phone1',
                    'required' => false,
                ]
            )
            ->add(
                'phone2',
                TextType::class,
                [
                    'attr' => [
                        'maxlength' => 20,
                    ],
                    'constraints' => [
                        new Length(max: 20),
                    ],
                    'label' => 'field.phone2',
                    'required' => false,
                ]
            )
            ->add(
                'phone3',
                TextType::class,
                [
                    'attr' => [
                        'maxlength' => 20,
                    ],
                    'constraints' => [
                        new Length(max: 20),
                    ],
                    'label' => 'field.phone3',
                    'required' => false,
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Member::class,
        ]);
    }
}

src/Controller/Member/MemberAddController.php
<?php

declare(strict_types=1);

namespace App\Controller\Member;

use App\Entity\Member;
use App\Form\MemberType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

final class MemberAddController extends AbstractController
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly TranslatorInterface $translator,
    ) {
    }

    #[Route('/member/add', name: 'app_member_add', methods: ['GET', 'POST'])]
    public function __invoke(Request $request): Response
    {
        $member = new Member();

        $form = $this->createForm(MemberType::class, $member);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($member);
            $this->entityManager->flush();

            $this->addFlash('success', $this->translator->trans('notification.member_added'));

            return $this->redirectToRoute('app_member_index');
        }

        return $this->render('member/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/Member/MemberEditController.php
<?php

declare(strict_types=1);

namespace App\Controller\Member;

use App\Form\MemberType;
use App\Repository\MemberRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

final class MemberEditController extends AbstractController
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly MemberRepository $memberRepository,
        private readonly TranslatorInterface $translator,
    ) {
    }

    #[Route(
        '/member/edit/{uuid}',
        name: 'app_member_edit',
        methods: ['GET', 'POST']
    )]
    public function __invoke(Request $request, string $uuid): Response
    {
        $member = $this->memberRepository->findOneBy(['uuid' => $uuid]);
        if (!$member) {
            throw new NotFoundHttpException();
        }

        $form = $this->createForm(MemberType::class, $member);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            $this->addFlash('success', $this->translator->trans('notification.member_updated'));

            return $this->redirectToRoute('app_member_show', [
                'uuid' => (string) $member->getUuid(),
            ]);
        }

        return $this->render('member/edit.html.twig', [
            'form' => $form->createView(),
            'member' => $member,
        ]);
    }
}

src/Controller/Member/MemberIndexController.php
<?php

declare(strict_types=1);

namespace App\Controller\Member;

use App\Form\MemberSearchType;
use App\Model\Pagination;
use App\Model\Search;
use App\Repository\MemberRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class MemberIndexController extends AbstractController
{
    public function __construct(private readonly MemberRepository $memberRepository)
    {
    }

    #[Route('/member', name: 'app_member_index', methods: ['GET'])]
    public function __invoke(Request $request): Response
    {
        $form = $this->createForm(MemberSearchType::class, null, ['method' => 'GET']);
        $form->handleRequest($request);
        $search = new Search($request->query->getInt('page'));
        $search->setFilters($form->getData());
        $members = $this->memberRepository->findBySearch($search);
        $pagination = new Pagination($members, $search, 'app_member_index');

        return $this->render('member/index.html.twig', [
            'form' => $form->createView(),
            'members' => $members,
            'pagination' => $pagination,
            'search' => $search,
        ]);
    }
}

src/Controller/Member/MemberShowController.php
<?php

declare(strict_types=1);

namespace App\Controller\Member;

use App\Repository\AttendanceRepository;
use App\Repository\MemberRepository;
use App\Repository\MembershipRepository;
use App\Repository\PromotionRepository;
use App\Repository\SeasonRepository;
use DateTimeImmutable;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Uid\Uuid;

final class MemberShowController extends AbstractController
{
    public function __construct(
        private readonly AttendanceRepository $attendanceRepository,
        private readonly MemberRepository $memberRepository,
        private readonly MembershipRepository $membershipRepository,
        private readonly PromotionRepository $promotionRepository,
        private readonly SeasonRepository $seasonRepository,
    ) {
    }

    #[Route(
        '/member/show/{uuid}',
        name: 'app_member_show',
        methods: ['GET']
    )]
    public function __invoke(string $uuid): Response
    {
        $member = $this->memberRepository->findByUuid(Uuid::fromString($uuid));
        if (!$member) {
            throw new NotFoundHttpException();
        }

        $attendances = null;
        $season = $this->seasonRepository->findByDate(new DateTimeImmutable());
        if ($season) {
            try {
                $currentMembership = $this->membershipRepository->findByMemberAndSeason($member, $season);
                $attendances = $this->attendanceRepository->findByMembership($currentMembership);
            } catch (NonUniqueResultException $exception) {
            }
        }

        $memberships = $this->membershipRepository->findByMember($member);
        $promotions = $this->promotionRepository->findByMember($member);

        return $this->render('member/show.html.twig', [
            'attendances' => $attendances,
            'member' => $member,
            'memberships' => $memberships,
            'promotions' => $promotions,
        ]);
    }
}

templates/member/add.html.twig
{% extends 'member/base.html.twig' %}

{% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}

{% block body %}
    <h1>{{ 'title.member_add'|trans }}</h1>
    {{ form_start(form) }}
    <div class="card mt-4">
        <div class="card-body">
            {{ form_widget(form) }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="fas fa-fw fa-save"></i>
                {{ 'action.save'|trans }}
            </button>
            <a href="{{ path('app_member_index') }}" class="btn btn-outline-secondary">
                <i class="fas fa-fw fa-times"></i>
                {{ 'action.back'|trans }}
            </a>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/member/base.html.twig
{% extends 'base.html.twig' %}

{% set activeMenu='member' %}

templates/member/edit.html.twig
{% extends 'member/base.html.twig' %}

{% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}

{% block body %}
    <h1>{{ 'title.member_edit'|trans }}</h1>
    {{ form_start(form) }}
    <div class="card mt-4">
        <div class="card-body">
            {{ form_widget(form) }}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="fas fa-fw fa-save"></i>
                {{ 'action.save'|trans }}
            </button>
            <a href="{{ path('app_member_show',{uuid:member.uuid}) }}" class="btn btn-outline-secondary">
                <i class="fas fa-fw fa-times"></i>
                {{ 'action.back'|trans }}
            </a>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/member/index.html.twig
{% extends 'member/base.html.twig' %}

{% block body %}
    <div class="d-flex flex-row align-items-center">
        <h1 class="flex-grow-1">{{ 'title.member_list'|trans }}</h1>
        <div>
            <a href="{{ path('app_member_add') }}" class="btn btn-outline-primary">
                <i class="fas fa-fw fa-plus"></i>
                {{ 'action.add'|trans }}
            </a>
        </div>
    </div>
    {{ form_start(form) }}
    <div class="mt-4 row align-items-end">
        <div class="col-12 col-xl-3">
            {{ form_label(form.firstName) }}
            {{ form_widget(form.firstName) }}
        </div>
        <div class="col-12 col-xl-3">
            {{ form_label(form.lastName) }}
            {{ form_widget(form.lastName) }}
        </div>
        <div class="col-12 col-xl-3">
            {{ form_label(form.season) }}
            {{ form_widget(form.season) }}
        </div>
        <div class="col-12 col-xl-2">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-fw fa-search"></i>
                {{ 'action.search'|trans }}
            </button>
        </div>
    </div>
    {{ form_end(form) }}
    <table class="table table-hover mt-4">
        <thead>
        <tr>
            <th>{{ 'field.first_name'|trans }}
            <th>{{ 'field.last_name'|trans }}
            <th>{{ 'field.gender'|trans }}</th>
            <th>{{ 'field.age'|trans }}</th>
            <th>{{ 'field.city'|trans }}</th>
            <th>{{ 'field.rank'|trans }}</th>
        </tr>
        </thead>
        <tbody>
        {% for member in members %}
            <tr data-url="{{ path('app_member_show',{uuid:member.uuid}) }}">
                <td>{{ member.firstname }}</td>
                <td>{{ member.lastname }}</td>
                <td>{{ ('gender.'~member.gender)|trans }}</td>
                <td>{{ member.age }}</td>
                <td>{{ member.city }}</td>
                <td>
                    {% if member.lastPromotion %}
                        <img src="{{ asset(rank_image(member.lastPromotion.rank)) }}"
                             alt="Image"
                             title="{{ member.lastPromotion.rank.name }}&#10;{{ member.lastPromotion.rank.description }}"
                             class="border">
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6" class="p-5 fst-italic text-center text-muted">{{ 'no_results'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include '_pagination.html.twig' with {pagination} only %}
{% endblock %}

templates/member/show.html.twig
{% extends 'member/base.html.twig' %}

{% block body %}
    <div class="d-flex flex-row align-items-center">
        <h1 class="flex-grow-1">{{ 'title.member_show'|trans }} : {{ member }}</h1>
        <div>
            <a href="{{ path('app_member_index') }}" class="btn btn-outline-secondary">
                <i class="fa fa-fw fa-angle-double-left"></i>
                {{ 'action.back'|trans }}
            </a>
        </div>
    </div>
    <div class="card mt-4">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <p><strong>{{ member.firstName }} {{ member.lastName }}</strong></p>
                    <address>
                        {{ member.streetAddress }}<br/>
                        {{ member.postCode }} {{ member.city }}
                    </address>
                </div>
                <div class="col-6">
                    <div class="mb-3"><i
                                class="fa fa-fw fa-birthday-cake"></i> {{ member.birthday|format_date('long') }}</div>
                    {% if member.phone0 %}
                        <div><i class="fa fa-fw fa-phone"></i> {{ member.phone0 }}</div>{% endif %}
                    {% if member.phone1 %}
                        <div><i class="fa fa-fw fa-phone"></i> {{ member.phone1 }}</div>{% endif %}
                    {% if member.phone2 %}
                        <div><i class="fa fa-fw fa-phone"></i> {{ member.phone2 }}</div>{% endif %}
                    {% if member.phone3 %}
                        <div><i class="fa fa-fw fa-phone"></i> {{ member.phone3 }}</div>{% endif %}
                </div>
            </div>
        </div>
        <div class="card-footer text-end">
            <a href="{{ path('app_member_edit',{uuid:member.uuid}) }}" class="btn btn-outline-primary">
                <i class="fa fa-fw fa-edit"></i>
                {{ 'action.edit'|trans }}
            </a>
        </div>
    </div>
    <h2 class="mt-5">Présences</h2>
    <div class="row">
        {% for attendance in attendances %}
            <div class="m-1 col-1 p-1 text-center attendance-bg-{% if attendance.state==2 %}present{% elseif attendance.state==1 %}apologized{% else %}absent{% endif %}">
                {{ attendance.start_at|format_date('short') }}
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-12 col-xl-6">
            <h2 class="mt-5">Adhésions</h2>
            <table class="table mt-1">
                <thead>
                <tr>
                    <th>{{ 'field.season'|trans }}</th>
                    <th>{{ 'field.level'|trans }}</th>
                    <th>{{ 'field.number'|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for membership in memberships %}
                    <tr data-url="{{ path('app_membership_edit',{uuid:membership.uuid}) }}">
                        <td>{{ membership.season.start|format_date('long') }}</td>
                        <td>{% if membership.level %}{{ membership.level.name }}{% endif %}</td>
                        <td>{{ membership.number }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3" class="p-5 fst-italic text-center text-muted">{{ 'no_results'|trans }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="text-center">
                <a href="{{ path('app_membership_add',{memberUuid:member.uuid}) }}" class="btn btn-outline-primary">
                    <i class="fas fa-fw fa-plus"></i>
                    {{ 'action.add'|trans }}
                </a>
            </div>
        </div>
        <div class="col-12 col-xl-6">
            <h2 class="mt-5">Promotions</h2>
            <table class="table mt-1">
                <thead>
                <tr>
                    <th>{{ 'field.nomination_date'|trans }}</th>
                    <th>{{ 'field.rank'|trans }}</th>
                    <th>{{ 'field.description'|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for promotion in promotions %}
                    <tr data-url="{{ path('app_promotion_edit',{uuid:promotion.uuid}) }}">
                        <td>{{ promotion.nominationDate|format_date('full')|capitalize }}</td>
                        <td>{{ promotion.rank.name }}</td>
                        <td><small class="text-muted">{{ promotion.rank.description }}</small></td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3" class="p-5 fst-italic text-center text-muted">{{ 'no_results'|trans }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="text-center">
                <a href="{{ path('app_promotion_add',{memberUuid:member.uuid}) }}" class="btn btn-outline-primary">
                    <i class="fas fa-fw fa-plus"></i>
                    {{ 'action.add'|trans }}
                </a>
            </div>
        </div>
    </div>
{% endblock %}